### ISSUE TITLE
Verse range link?

### ISSUE THREAD

**Issue by 3ceepio** [pmbauer/av-obsidian#1]
Is it possible to link >1 verse e.g. a range of verses in a single reference? Thanks

**Comment by pmbauer** [comment]
No. It isn't possible using Obsidian internal links. You could use
templater or a plug-in to generate multiple links. I just use aliases
and link to the first verse of a range in my notes.

[[Genesis 1#^1|Genesis 1:1-3]]

On May 16, 2022, GitHub ***@***.***> wrote:
> Is it possible to link >1 verse e.g. a range of verses in a single
> reference? Thanks
>

—
Reply to this email directly, view it on GitHub
<https://github.com/pmbauer/av-obsidian/issues/1>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AADOXTCHGWQHVPLAM4XOTQTVKLCP7ANCNFSM5WC5TLJA>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>
